some imp function 

In [21]:
import numpy as np 

In [22]:
arr = np.array([4,10,6,45,8,0,0])

In [23]:
arr

array([ 4, 10,  6, 45,  8,  0,  0])

In [24]:
np.sort(arr)


array([ 0,  0,  4,  6,  8, 10, 45])

In [25]:
np.count_nonzero(arr)

5

In [26]:
np.where(arr > 6) #give indexes

(array([1, 3, 4]),)

In [27]:
#numpy opy and view

In [28]:
arr

array([ 4, 10,  6, 45,  8,  0,  0])

In [30]:
np.copy(arr)

array([ 4, 10,  6, 45,  8,  0,  0])

In [32]:
b = arr.view()

In [33]:
b

array([ 4, 10,  6, 45,  8,  0,  0])

In [34]:
arr

array([ 4, 10,  6, 45,  8,  0,  0])

numpy liner algebra that will be used in ml 

In [35]:
arr1 = np.random.randint([[2,3],[4,5]])

In [36]:
arr2 = np.random.randint([[2,3],[4,5]])

In [37]:
np.dot(arr1,arr2)

array([[ 0,  0],
       [12,  4]])

In [38]:
arr1@arr2

array([[ 0,  0],
       [12,  4]])