**NumPy** (Numerical Python) is a fundamental Python library for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a vast collection of mathematical functions to operate on these arrays. NumPy is a core library in the Python data science ecosystem and serves as the foundation for many other data science libraries.

Here are some key features of NumPy:

1. **N-dimensional array (ndarray)**: NumPy's most important data structure is the `ndarray`, which is a multi-dimensional array. These arrays can be one-dimensional (like a list), two-dimensional (like a matrix), or have even more dimensions. The ndarray allows efficient storage and manipulation of large datasets, making it suitable for numerical computations.

2. **Mathematical functions**: NumPy provides a wide range of mathematical functions that operate element-wise on ndarrays. These include arithmetic operations, trigonometric functions, statistical operations, linear algebra routines, and much more.

3. **Broadcasting**: Broadcasting is a powerful feature in NumPy that allows operations between arrays of different shapes and dimensions. It helps to perform operations efficiently without needing to explicitly write loops.

4. **Integration with C/C++ and Fortran**: NumPy allows seamless integration with code written in C, C++, or Fortran, enabling high-performance computations and easy integration with other libraries.

5. **Random number generation**: NumPy includes tools for generating random numbers from various probability distributions, which are essential for many statistical simulations.

Data scientists use NumPy extensively in their work due to its efficient array processing capabilities and mathematical functions. Here are some common use cases of NumPy in data science:

1. **Data manipulation**: NumPy allows data scientists to efficiently manipulate and transform large datasets. You can perform operations such as filtering, reshaping, and merging data using NumPy's array functions.

2. **Numerical computations**: NumPy provides an extensive set of mathematical functions that enable data scientists to perform a wide range of computations, from simple arithmetic operations to complex mathematical modeling.

3. **Array-based computations**: NumPy's array operations are optimized for performance, making it a suitable choice for numerical computations and simulations.

4. **Data cleaning and preprocessing**: NumPy is often used for data cleaning tasks, such as handling missing values, outlier detection, and data normalization.

5. **Statistical analysis**: NumPy integrates well with other data science libraries like pandas and SciPy to perform advanced statistical analysis.

6. **Machine learning**: NumPy arrays are commonly used as input data for machine learning algorithms implemented in libraries like scikit-learn and TensorFlow.

To use NumPy in your Python data science projects, you need to first install it using `pip`:

```
pip install numpy
```

Then, you can import it in your Python script or Jupyter Notebook:

```python
import numpy as np
```

Once imported, you can create ndarrays, perform array operations, and use NumPy's mathematical functions for data manipulation and analysis.

In [2]:
#Numpy numerical python 
#we use it for numarical computation in arrays and 
import numpy as np

In [3]:
l = [1,2,3,4]

In [4]:
# If we want to convert list into an arry we can do it using arry function 

ar = np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [6]:
# one dimentional arry 
ar = np.array(l)



In [7]:
# two dimentional arry 
np.array([[2,3],[5,6]])

array([[2, 3],
       [5, 6]])

In [8]:
ar1

NameError: name 'ar1' is not defined

In [9]:
#we can also use asarry and asanyarray function 


In [10]:
c = ar1


NameError: name 'ar1' is not defined

In [11]:
c

NameError: name 'c' is not defined

In [12]:
c[0] = 5

NameError: name 'c' is not defined

In [13]:
a = np.array([1,2,3,4,5])

In [14]:
a

array([1, 2, 3, 4, 5])

In [15]:
#we can coppy the array
d = np.copy(a)

In [16]:
d

array([1, 2, 3, 4, 5])

In [17]:
a[0]=532

In [18]:
a

array([532,   2,   3,   4,   5])

In [19]:
d # will not chage bcz it is deep copy and it creat a new location 

array([1, 2, 3, 4, 5])

In [20]:
# To genrate diffrent types of array
np.fromfunction(lambda i , j : i == j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [21]:
# another function 
itrable = (i*i  for i in range (5))
np.fromiter(itrable , float)

array([ 0.,  1.,  4.,  9., 16.])

In [22]:
np.fromstring('4,5',sep = ',')

array([4., 5.])

In [23]:
# we can chek the dimaention of an array 
a.ndim

1

In [24]:
ar2 = np.array([[45,6,7,8],[894,6,5,64]])

In [25]:
ar2

array([[ 45,   6,   7,   8],
       [894,   6,   5,  64]])

In [26]:
ar2.ndim

2

In [27]:
a.size

5

In [28]:
ar2.size

8

In [29]:
ar2.shape

(2, 4)

In [30]:
a.shape

(5,)

In [31]:
ar2.dtype

dtype('int64')

In [32]:
list(range(0.1 , 5))

TypeError: 'float' object cannot be interpreted as an integer

In [33]:
list(range(5))

[0, 1, 2, 3, 4]

In [34]:
#we can use float also in array to creat it 
np.arange(2.4,5.8,.3)

array([2.4, 2.7, 3. , 3.3, 3.6, 3.9, 4.2, 4.5, 4.8, 5.1, 5.4, 5.7])

In [35]:
list(np.arange(2.4,5.8,.3))

[2.4,
 2.6999999999999997,
 2.9999999999999996,
 3.2999999999999994,
 3.599999999999999,
 3.899999999999999,
 4.199999999999999,
 4.499999999999998,
 4.799999999999999,
 5.099999999999998,
 5.399999999999999,
 5.6999999999999975]

In [36]:
np.linspace(5.0,6.0)

array([5.        , 5.02040816, 5.04081633, 5.06122449, 5.08163265,
       5.10204082, 5.12244898, 5.14285714, 5.16326531, 5.18367347,
       5.20408163, 5.2244898 , 5.24489796, 5.26530612, 5.28571429,
       5.30612245, 5.32653061, 5.34693878, 5.36734694, 5.3877551 ,
       5.40816327, 5.42857143, 5.44897959, 5.46938776, 5.48979592,
       5.51020408, 5.53061224, 5.55102041, 5.57142857, 5.59183673,
       5.6122449 , 5.63265306, 5.65306122, 5.67346939, 5.69387755,
       5.71428571, 5.73469388, 5.75510204, 5.7755102 , 5.79591837,
       5.81632653, 5.83673469, 5.85714286, 5.87755102, 5.89795918,
       5.91836735, 5.93877551, 5.95918367, 5.97959184, 6.        ])

In [37]:
# we can also create zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [38]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [40]:
ar3 = np.ones(5)

In [41]:
ar3

array([1., 1., 1., 1., 1.])

In [42]:
ar3*4

array([4., 4., 4., 4., 4.])

In [43]:
ar3 + 5

array([6., 6., 6., 6., 6.])

In [44]:
np.empty(5)

array([6., 6., 6., 6., 6.])

In [45]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
#if we want to get log then 
np.logspace(7,5 , base = 2)

array([128.        , 124.4294069 , 120.95841642, 117.58425012,
       114.30420706, 111.11566165, 108.01606154, 105.00292557,
       102.07384181,  99.2264656 ,  96.45851768,  93.76778239,
        91.15210586,  88.60939429,  86.13761233,  83.73478136,
        81.39897798,  79.12833244,  76.92102715,  74.77529521,
        72.68941901,  70.66172888,  68.69060168,  66.77445958,
        64.91176877,  63.10103819,  61.34081842,  59.62970042,
        57.96631451,  56.34932918,  54.77745007,  53.24941894,
        51.76401263,  50.32004211,  48.91635153,  47.55181725,
        46.22534701,  44.93587901,  43.68238104,  42.46384973,
        41.27930966,  40.12781264,  39.00843693,  37.9202865 ,
        36.8624903 ,  35.8342016 ,  34.83459728,  33.86287719,
        32.91826347,  32.        ])

# Usefull functions 
## we will use it in ml

In [47]:
# To creat a rendom number 
arr = np.random.randn(3,4) #use mean and standard daviation

In [48]:
# if we have to store it in dataframe then 


In [49]:
import pandas as pd 


In [50]:
pd.DataFrame(arr)

0         1         2         3
0  0.132787 -0.861607 -0.311540 -0.652706
1 -0.420912 -0.985917 -0.644775 -0.131391
2 -0.113217 -1.032330  0.582829  0.249561

In [51]:
arr1 = np.random.rand(3,4) #rendom data

In [52]:
arr1

array([[0.13832563, 0.09089006, 0.29265151, 0.28910853],
       [0.800816  , 0.36066581, 0.09069365, 0.45532679],
       [0.7277461 , 0.30278434, 0.94025631, 0.45145764]])

In [53]:
pd.DataFrame(np.random.randint(1,110 ,(300,400)))
                                       

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     74   63   30   32   69   12    3   66   84   10  ...   88   25    1   
1     55    7  101   89   64   51   45   22   89  105  ...   33   52   13   
2     32   36  103   50   31   90  108   47   71   89  ...   94   47   73   
3     70   96   89   90   44   70   91   54   87    8  ...   61   29   50   
4      7   33   79   98   21   31   32   34   32  102  ...   82  104   29   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   86   53   97   59  106    6   44   59   67   84  ...   48   11   26   
296   57   61   98   85   22   22   92   84    3   28  ...   94   95   50   
297   21   10   17   92   91  101   38   28   88   57  ...   86   65   16   
298    9   16   24    9   24   13    2   59   51   81  ...   74   33   89   
299    3   86   66    5   26   29   83   39    8   36  ...   20   25   70   

     393  394  395  396  397  398  399  
0     13   52   27   13   57   22   60  
1      8   83   27   51   31   78    4  
2     50   48   29   37   26   71   77  
3     28   98   45   66   69   73   40  
4      4   43   52    2   70   12    9  
..   ...  ...  ...  ...  ...  ...  ...  
295   30   46   88   19    5   74  107  
296   18   11   14   51    4   55   31  
297   58   76   24   19   55   42   86  
298   73   36   95    9   17   93   90  
299   29  101    7   99   90   61    5  

[300 rows x 400 columns]

In [54]:
#we can also save it 
pd.DataFrame(np.random.randint(1,110 ,(300,400))).to_csv('test.csv')

In [55]:
arr3 = np.random.rand(2,6)

In [56]:
arr3

array([[0.34373872, 0.53922084, 0.5630001 , 0.51292506, 0.85215568,
        0.73408   ],
       [0.98035693, 0.5030891 , 0.82026833, 0.47490286, 0.0764904 ,
        0.37601911]])

In [57]:
arr3.reshape(6,2)

array([[0.34373872, 0.53922084],
       [0.5630001 , 0.51292506],
       [0.85215568, 0.73408   ],
       [0.98035693, 0.5030891 ],
       [0.82026833, 0.47490286],
       [0.0764904 , 0.37601911]])

In [58]:
arr3.reshape(6,8)

ValueError: cannot reshape array of size 12 into shape (6,8)

In [59]:
arr4 = np.random.randint(1,100 , (5,5))

In [60]:
arr4

array([[21, 36, 27, 53, 76],
       [63, 57, 89, 63, 91],
       [ 2, 77, 71, 51, 84],
       [67, 80, 88, 32, 66],
       [44,  9, 40, 18, 83]])

In [61]:
arr4>50

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [False, False, False, False,  True]])

In [62]:
arr4[arr4>50]

array([53, 76, 63, 57, 89, 63, 91, 77, 71, 51, 84, 67, 80, 88, 66, 83])

In [63]:
arr4[3:4]

array([[67, 80, 88, 32, 66]])

In [64]:
ary = np.array([1,2,3,4])


In [65]:
ary2  = np.array([5,6,7,8])

In [66]:
 ary + ary2

array([ 6,  8, 10, 12])

In [67]:
ary2 - ary

array([4, 4, 4, 4])

In [68]:
ary2 * ary

array([ 5, 12, 21, 32])

In [69]:
# we can do matricx multiplication using@
ary @ ary2


70

In [70]:
# Brodcasting 

In [71]:
ary3 = np.zeros((3,4))

In [72]:
ary3


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
row = np.array([1,2,3,4])

In [74]:
ary3 + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [75]:
cal = np.array([[1,2,3,4]])

In [76]:
cal.T

array([[1],
       [2],
       [3],
       [4]])

In [77]:
ary3 + cal

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [78]:
np.sqrt(ary3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])