In [1]:
#array manupilation


In [2]:
import numpy as np


In [3]:
arr = np.random.randint(1,10,(3,4))

In [4]:
arr

array([[2, 6, 2, 7],
       [9, 8, 2, 7],
       [6, 1, 3, 1]])

In [5]:
arr.reshape(6,2)

array([[2, 6],
       [2, 7],
       [9, 8],
       [2, 7],
       [6, 1],
       [3, 1]])

In [6]:
arr.T

array([[2, 9, 6],
       [6, 8, 1],
       [2, 2, 3],
       [7, 7, 1]])

In [7]:
#we can convert 2d into 1 d
arr.flatten()

array([2, 6, 2, 7, 9, 8, 2, 7, 6, 1, 3, 1])

In [8]:
arr.ndim

2

In [9]:
arr2 = np.array([2,3,5,4])

In [10]:
arr2.ndim

1

In [11]:
np.expand_dims(arr2,axis=1)

array([[2],
       [3],
       [5],
       [4]])

In [12]:
data = np.array([[1],[2],[3,]])

In [13]:
data

array([[1],
       [2],
       [3]])

In [14]:
data.squeeze()

array([1, 2, 3])

In [15]:
np.repeat(arr2 , 3)

array([2, 2, 2, 3, 3, 3, 5, 5, 5, 4, 4, 4])

In [17]:
np.roll(arr2 , 2)

array([5, 4, 2, 3])

In [18]:
np.diag(arr2)

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 4]])

In [19]:
arr +arr2

array([[ 4,  9,  7, 11],
       [11, 11,  7, 11],
       [ 8,  4,  8,  5]])

In [20]:
arr *arr2

array([[ 4, 18, 10, 28],
       [18, 24, 10, 28],
       [12,  3, 15,  4]])

In [21]:
arr3 = np.array(["kuldeep","mAhiR "])

In [22]:
np.char.upper(arr3)

array(['KULDEEP', 'MAHIR '], dtype='<U7')

In [24]:
np.char.title(arr3)

array(['Kuldeep', 'Mahir '], dtype='<U7')

In [26]:
np.power(arr , 2)

array([[ 4, 36,  4, 49],
       [81, 64,  4, 49],
       [36,  1,  9,  1]])

In [27]:
np.max(arr)

9